name: Run a command
on: repository_dispatch
jobs:
  run:
    if: github.event.action == 'run'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: ${{ github.event.client_payload.command }}
